export default  {
  ON_BOARDING_SCREEN: 'ON_BOARDING_SCREEN',
  USER_TYPE_SCREEN: 'USER_TYPE_SCREEN',
  SIGN_IN_MEMBER_SCREEN: 'SIGN_IN_MEMBER_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
  FORGOT_PASSWORD_SCREEN: 'FORGOT_PASSWORD_SCREEN',
  OTP_SCREEN: 'OTP_SCREEN',
  RESET_PASSWORD: 'RESET_PASSWORD',
  //Member Screen
  HOME_MEMBER_SCREEN: 'HOME_MEMBER_SCREEN',
  CHAT_SCREEN: 'CHAT_SCREEN',
  NEW_CHAT_ROOM_SCREEN: 'NEW_CHAT_ROOM_SCREEN',
} 


